### ISSUE TITLE
Support for Riot.js

### ISSUE THREAD

**Issue by phillip-haydon** [LiuJi-Jim/vscode-vue#1]
Hey, your Vue extension works great with Riot.js. I literally want to take it and change the extension to `.tag` for support with Riot, do you mind if I fork and publish this?

**Comment by LiuJi-Jim** [comment]
Hi, @phillip-haydon 
Sorry for I know little about Riot.js. Obviously, vscode-vue is designed to work with Vue.js. In the latest PR we have Vue.js code snippets. This extension MAY work with other libs/frameworks well, but that won't be our objective.
I'm very glad if you like this tool. You may fork and reuse the code and publish a new extension for Visual Studio Code if needed.
