### ISSUE TITLE
<style lang="scss"> is not highlighting

### ISSUE THREAD

**Issue by zanjs** [LiuJi-Jim/vscode-vue#13]
This script tag In front of，style is not highlighting

![2016-05-16 11 54 39](https://cloud.githubusercontent.com/assets/12947276/15279960/0d469d2c-1b5d-11e6-9052-c7665dbae253.png)

This script tag behind，style is highlighting

![2016-05-16 11 55 00](https://cloud.githubusercontent.com/assets/12947276/15279965/173e4082-1b5d-11e6-9b22-17801166235a.png)

**Comment by LiuJi-Jim** [comment]
see #12
