### ISSUE TITLE
<style lang="stylus"> syntax highlight is not valid

### ISSUE THREAD

**Issue by externuz** [LiuJi-Jim/vscode-vue#14]
`<style lang="stylus">` in .vue files
^ indent does not work, syntax highlight is not valid

**Comment by Elementrat** [comment]
Seeing this as well.

**Comment by LiuJi-Jim** [comment]
fixed in 0.1.4

P.S. VSCode doesn't defaultly support stylus, you may need to install a stylus extension.
vscode-vue is tested to work with [sysoev/language-stylus](https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus).
