### ISSUE TITLE
<style>...</style>标签中，不支持sass，less等样式的语法提示

### ISSUE THREAD

**Issue by mmzhi** [LiuJi-Jim/vscode-vue#15]

**Comment by LiuJi-Jim** [comment]
fixed in 0.1.4

P.S. VSCODE doesn't defaultly support sass. You may need to install a sass extension.
vscode-vue is tested to work with [Robin Bentley/Sass](https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented)

**Comment by soakit** [comment]
![image](https://cloud.githubusercontent.com/assets/11240668/21179269/499fc1d6-c22e-11e6-82ae-48ddaa703249.png)
not work...

**Comment by cike8899** [comment]
但是在类名嵌套的时候会报错的！这个可以修复吗？
