### ISSUE TITLE
Still cannot works。。

### ISSUE THREAD

**Issue by unhealthy** [LiuJi-Jim/vscode-vue#4]
Well actually in my vscode the syntax highlight don't work well.

It seems that the es6 is not supported in 'script' tag

![syntax highlight is wrong](https://raw.githubusercontent.com/unhealthy/vscode-vue/master/images/broken-screenshop.png)

Could you share that how to fix it?

**Comment by LiuJi-Jim** [comment]
@unhealthy it seems that ES2015 `export` syntax brakes the syntax highlights. maybe a new version of `.tmLanguage` will be needed to be compatible with the new language features (maybe more than `export`).
currently vscode-vue uses the `vue.tmLanguage` from [vuejs/vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight). but vue-syntax-highlight seems to work well with ES2015. so maybe more time will be needed for testing the `.tmLanguage` file and VSC's syntax highlighting.

**Comment by unhealthy** [comment]
@LiuJi-Jim yes it needs further development to support vuejs well in vscode.
I have try again and it seems it's because the syntax of `default` in vscode. When I change another symbol, it works well.
![alt](https://raw.githubusercontent.com/unhealthy/vscode-vue/master/images/broken-screenshop2.png)

Since `.vue` file contains `HTML` code and `JavaScript` code, I wonder if there's a way to extend the default language support of `HTML` and `JavaScript` from vscode. And I [ask to Vscode team](https://github.com/Microsoft/vscode/issues/1689), but they say "The ways to reuse language functionality are currently very limited."

**Comment by codehz** [comment]
还有就是这个也是这样，当script中含有export default时，下方的\<style\>会出问题
![l 6 ut f7z 7v p6s e ah](https://cloud.githubusercontent.com/assets/13158903/12346106/52eade32-bb8c-11e5-8aac-74671f7cbb96.png)

**Comment by DitlevHB** [comment]
This is still an issue.
I have attempted to fix this issue, but my knowledge in building syntax highlighting is too poor.

I thinking about addressing this in the original syntax highlight repo, since it looks like this issue doesn't get much attention.
https://github.com/vuejs/vue-syntax-highlight

**Comment by LiuJi-Jim** [comment]
@DitlevHB 
I tried to fix the highlighting by updating the latest `.tmLanguage` file of [vuejs/vue-syntax-highlighting](https://github.com/vuejs/vue-syntax-highlight) but failed. 

It seems that visual studio code doesn't apply syntax parsing on `.vue` files' `<script>` tags correctly. Because I can't get any JS syntax errors, even can't get full featured JavaScript IntelliSense in `.vue` files, which works perfectly in `.html` files as expected.

I still do not know how VSC's IntelliSense works in `.html` files but not in `.vue` files. I tried to copy codes from VSC's `.html` syntax files but still doesn't work.

**Comment by vmrocha** [comment]
Do you think that there is any change of this issue get solved soon? Are you using another tool? How are you dealing with this?

**Comment by LiuJi-Jim** [comment]
@vmrocha 
Sorry I didn't solve this. I'm still trying to find out why IntelliSense failed in `.vue` files.

Currently I manually change the syntax to `.html` when writing `.vue` files.

I tried to map `.vue` to `.html` language in the extension automatically, but thus will cause an error, I'm trying to fix it.

**Comment by unhealthy** [comment]
Maybe this is because there is language server run behind to support the IntelliSense of `.html`. Maybe we need to  programmatically make calls to API of vscode to support language feature rather than simply based on regex match.

https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by LiuJi-Jim** [comment]
see #12
