### ISSUE TITLE
Syntax hilighting only partially working...

### ISSUE THREAD

**Issue by mkelley82** [LiuJi-Jim/vscode-vue#8]
As you can see it is only partially highlighting the code in my .vue file. I'm using VS Code 1.0.0 with vscode-vue 0.1.2.

![capture](https://cloud.githubusercontent.com/assets/677720/14939226/d1af1972-0f0b-11e6-8075-0528d3583187.PNG)

**Comment by LiuJi-Jim** [comment]
VS code (seems) doesn't activate full-featured JavaScript language support for embeded `<script>` tags.
I still didn't find a way to activate it.
For more information see the latest README.

**Comment by LiuJi-Jim** [comment]
#12
